apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: summarizer-secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /workspaces/aca-dapr-openai-workshop/dapr/summarizer-secrets.json
  - name: nestedSeparator
    value: ":"